# Site settings
author: Jose Melero Martinez
title: Starting to Code
header-img: img/home-bg.png
email: jmelero08@gmail.com
copyright_name: Jose Melero Martinez
description: > # this means to ignore newlines until "baseurl:"
  Just beginning 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmelero08

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
